import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Globe2, MonitorPlay, LayoutList } from 'lucide-react';
import folderCodeIcon from '../../../lucide/folder-code.svg';
export function AuthBranding() {
    return (_jsxs("div", { className: "flex flex-col", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("img", { src: folderCodeIcon, alt: "", className: "h-8 w-8 xl:h-9 xl:w-9" }), _jsx("span", { className: "font-[Geist_Mono] text-[20px] font-semibold text-[#155DFC]", children: "Exam App" })] }), _jsxs("h2", { className: "mt-16 font-sans text-[24px] font-bold leading-tight text-foreground xl:mt-20 xl:text-[30px] xl:leading-[38px]", children: ["Empower your learning journey", _jsx("br", {}), "with our smart exam platform."] }), _jsxs("div", { className: "mt-10 flex flex-col gap-8 xl:mt-12 xl:gap-10", children: [_jsx(FeatureItem, { icon: _jsx(Globe2, { className: "h-5 w-5 xl:h-6 xl:w-6" }), title: "Tailored Diplomas", description: "Choose from specialized tracks like Frontend, Backend, and Mobile Development." }), _jsx(FeatureItem, { icon: _jsx(MonitorPlay, { className: "h-5 w-5 xl:h-6 xl:w-6" }), title: "Focused Exams", description: "Access topic-specific tests including HTML, CSS, JavaScript, and more." }), _jsx(FeatureItem, { icon: _jsx(LayoutList, { className: "h-5 w-5 xl:h-6 xl:w-6" }), title: "Smart Multi-Step Forms", description: "Choose from specialized tracks like Frontend, Backend, and Mobile Development." })] })] }));
}
function FeatureItem({ icon, title, description, }) {
    return (_jsxs("div", { className: "flex items-start gap-3", children: [_jsx("div", { className: "flex h-10 w-10 shrink-0 items-center justify-center border border-blue-300 text-[#155DFC] xl:h-11 xl:w-11", children: icon }), _jsxs("div", { className: "flex flex-col gap-1", children: [_jsx("p", { className: "font-[Geist_Mono] text-[20px] font-semibold text-[#155DFC]", children: title }), _jsx("p", { className: "font-[Geist_Mono] text-[16px] font-normal leading-[100%] text-muted-foreground", children: description })] })] }));
}
